### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by sagehartly** [sagehartly/assignment-5#1]
@thomasjbradley I have a strange white bar in between the text and the image of the corn. When I inspect the elements and hover over the image and then the text, the white bar is not coloured either time so I'm not sure what element it is part of. I adjusted the padding and the margin and it doesn't make a difference.

This is the first time I've made an issue so let me know if I'm missing anything! :+1: 

My website so far: http://sagehartly.github.io/assignment-5/

Thank  you!
- Sage Mosurinjohn (Group 2)

**Comment by thomasjbradley** [comment]
I think it's just a matter of what the orange background colour is being applied to. Right now each individual element has the orange bg.

But what if you wrapped them all in another element and applied the orange bg to it instead?

**Comment by sagehartly** [comment]
OK great, thank you! That worked! It took some re-organizing because I was using the div instead of the header tag at the top but I think it's worked out now. Thanks again for the quick reply!
